// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esozoaohiqeldippzxms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzb3pvYW9oaXFlbGRpcHB6eG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MzQ3NzEsImV4cCI6MjA3ODExMDc3MX0.7C-tZFF3VtotrwXZSqtbes0OzprL0hXlAVYyDBed7Qw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});